export const TitlesForm = [
  {
    id: 1,
    name: "userName",
    type: "text",
    placeholder: "Nombres y Apellidos",
    errorMessage:
      "El nombre completo debe contener, minimo un nombre y dos apellidos",
    label: "Nombres y Apellidos",
    pattern: `^[a-zA-Z]+(([',. -][a-zA-Z ])?[a-zA-Z]*)*$`,
    required: true,
  },
  {
    id: 2,
    name: "email",
    type: "email",
    placeholder: "Email",
    errorMessage: "Ingresa un email valido",
    label: "Email",
    pattern: "^[^s@]+@[^s@]+.[^s@]+$",
    required: true,
  },
  {
    id: 3,
    name: "phone",
    type: "number",
    placeholder: "Telefono - Celular",
    errorMessage: "Ingresa un numero de telefono o celular de 8 caracteres",
    label: "Telefono - Celular",
    pattern: `^[0-9]{8}$`,
    required: true,
  },
  {
    id: 4,
    name: "creditCard",
    type: "number",
    placeholder: "Tarjeta de Credito",
    label: "Tarjeta de Credito",
  },
  {
    id: 5,
    name: "numberCreditCard",
    type: "number",
    placeholder: "Numero de Tarjeta de Credito",
    label: "Numero de Tarjeta de Credito",
  },
  {
    id: 6,
    name: "company",
    type: "text",
    placeholder: "Empresa/Institución)",
    label: "Empresa/Institución)",
  },
  {
    id: 7,
    name: "phoneCompany",
    type: "number",
    placeholder: "Telefono(Empresa/Institución)",
    label: "Telefono(Empresa/Institución))",
  },
  {
    id: 8,
    name: "reservadoPor",
    type: "text",
    placeholder: "Nombre completo del reservante",
    errorMessage:
      "El nombre completo debe contener, minimo un nombre y dos apellidos, sin caracteres especiales, tampoco numeros!",
    label: "Reservado por:",
    pattern: `^[a-zA-Z]+(([',. -][a-zA-Z ])?[a-zA-Z]*)*$`,
    required: true,
  },
  {
    id: 9,
    name: "fechaReserva",
    type: "date",
    placeholder: "Fecha de Reserva",
    errorMessage: "Ingresa una fecha valida",
    label: "Fecha de reserva",
    required: true,
  },

  {
    id: 10,
    name: "observations",
    type: "text",
    placeholder: "Observaciones",
    label: "Observaciones",
  },
  {
    id: 11,
    name: "fechaIngreso",
    type: "date",
    placeholder: "Fecha de Ingreso",
    errorMessage: "Ingresa una fecha valida",
    label: "Fecha de ingreso",
    required: true,
  },
  {
    id: 12,
    name: "fechaSalida",
    type: "date",
    placeholder: "Fecha de Salida",
    errorMessage: "Ingresa una fecha valida",
    label: "Fecha de salida",
    required: true,
  },
];
